INSERT INTO InsuranceProvider (ID, Name) VALUES (3, 'Cigna');
INSERT INTO InsuranceProvider (ID, Name) VALUES (4, 'Humana');
INSERT INTO InsuranceProvider (ID, Name) VALUES (5, 'UnitedHealthcare');

INSERT INTO Policy (ID, InsuranceProviderID, Name, Deductible) VALUES (3, 3, 'Cigna - Standard Plan', '500');
INSERT INTO Policy (ID, InsuranceProviderID, Name, Deductible) VALUES (4, 4, 'Humana - Standard Plan', '500');
INSERT INTO Policy (ID, InsuranceProviderID, Name, Deductible) VALUES (5, 5, 'UnitedHealthcare - Standard Plan', '500');

INSERT INTO ProcedureType (ID, Name, Description) VALUES (24, 'Physical Therapy', 'Physical Therapy');

INSERT INTO PolicyCoverage (ID, PolicyID, ProcedureTypeID, Description, LinkToOriginal, StartDate, EndDate, DocumentURL, AddedDate) VALUES
(23, 2, 24, 'Physical Therapy', 'https://www.aetna.com/cpb/medical/data/300_399/0325.html', '2025-01-01', '2025-12-31', 'docs/aetna/Physical Therapy.pdf', CURRENT_TIMESTAMP);

INSERT INTO PolicyCoverage (ID, PolicyID, ProcedureTypeID, Description, LinkToOriginal, StartDate, EndDate, DocumentURL, AddedDate) VALUES
(24, 3, 24, 'Therapy Services - Physical Therapy',  'https://static.cigna.com/assets/chcp/pdf/coveragePolicies/medical/cpg135_physical_therapy.pdf',
 '2025-01-01', '2025-12-31', 'docs/cigna/Therapy Services Physical Therapy.pdf', CURRENT_TIMESTAMP);

INSERT INTO PolicyCoverage (ID, PolicyID, ProcedureTypeID, Description, LinkToOriginal, StartDate, EndDate, DocumentURL, AddedDate) VALUES
(25, 4, 24, 'Outpatient Rehabilitation (Physical Therapy, Occupational Therapy)', 'https://mcp.humana.com/tad/TAD_New/Search.aspx?criteria=Outpatient+Rehabilitation&searchtype=freetext&policyType=both', '2025-01-01', '2025-12-31',  'docs/humana/Outpatient Rehabilitation (Physical Therapy, Occupational Therapy).pdf', CURRENT_TIMESTAMP);

INSERT INTO PolicyCoverage (ID, PolicyID, ProcedureTypeID, Description, LinkToOriginal, StartDate, EndDate, DocumentURL, AddedDate) VALUES
(26, 5, 24, 'Habilitation and Rehabilitation Therapy (Occupational, Physical and Speech)', 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/comm-medical-drug/habilitative-services-outpatient-rehabilitation-therapy.pdf', '2025-01-01', '2025-12-31', 'docs/unitedheathcare/Habilitation and Rehabilitation Therapy (Occupational, Physical and Speec).pdf', CURRENT_TIMESTAMP);

INSERT INTO PolicyCoverage (ID, PolicyID, ProcedureTypeID, Description, LinkToOriginal, StartDate, EndDate, DocumentURL, AddedDate) VALUES
(27, 3, 21, 'Hearing Aids', 'https://static.cigna.com/assets/chcp/pdf/coveragePolicies/medical/mm_0093_coveragepositioncriteria_hearing_aids.pdf', '2025-01-01', '2025-12-31', 'docs/cigna/Hearing Aids.pdf', CURRENT_TIMESTAMP);

-- Cancer Vaccines
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(58, 14, 'Z23', 'Encounter for immunization', 'ICD-10', 'covered'),
(59, 14, 'C00.0-C96.9',   'Malignant neoplasms', 'ICD-10', 'not_covered'),
(60, 14, 'D00.00-D09.9', 'Carcinoma in situ', 'ICD-10', 'not_covered');

-- Hearing Aids
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(61, 20, '0951T', 'Totally implantable active middle ear hearing implant; initial placement, including mastoidectomy, placement of and attachment to sound processor', 'CPT', 'covered'),
(62, 20, '0952T', 'Totally implantable active middle ear hearing implant; revision or replacement, with mastoidectomy and replacement of sound processor', 'CPT', 'covered'),
(63, 20, '0953T', 'Totally implantable active middle ear hearing implant; revision or replacement, without mastoidectomy and replacement of sound processor', 'CPT', 'covered'),
(64, 20, '0954T', 'Totally implantable active middle ear hearing implant; replacement of sound processor only, with attachment to existing transducers', 'CPT', 'covered'),
(65, 20, '0955T', 'Totally implantable active middle ear hearing implant; removal, including removal of sound processor and all implant components', 'CPT', 'covered'),
(66, 20, '92628', 'Evaluation for hearing aid candidacy, unilateral or bilateral, including review and integration of audiologic function tests; first 30 minutes', 'CPT', 'related'),
(67, 20, '92629', 'Evaluation for hearing aid candidacy; each additional 15 minutes', 'CPT', 'related'),
(68, 20, '92631', 'Hearing aid selection services, unilateral or bilateral, including review of audiologic function tests and hearing aid candidacy evaluation; first 30 minutes', 'CPT', 'related'),
(69, 20, '92632', 'Hearing aid selection services; each additional 15 minutes', 'CPT', 'related'),
(70, 20, '92634', 'Hearing aid fitting services, unilateral or bilateral, including device analysis, programming, verification, counseling, orientation, and training; first 60 minutes', 'CPT', 'related'),
(71, 20, '92635', 'Hearing aid fitting services; each additional 15 minutes', 'CPT', 'related'),
(72, 20, '92636', 'Hearing aid post-fitting follow-up services, unilateral or bilateral, including confirmation of physical fit, validation of patient benefit and performance; first 30 minutes', 'CPT', 'related'),
(73, 20, '92637', 'Hearing aid post-fitting follow-up services; each additional 15 minutes', 'CPT', 'related'),
(74, 20, '92638', 'Behavioral verification of amplification including aided thresholds, functional gain, speech-in-noise', 'CPT', 'related'),
(75, 20, '92639', 'Hearing-aid measurement, verification with probe-microphone', 'CPT', 'related'),
(76, 20, '92641', 'Hearing device verification, electroacoustic analysis', 'CPT', 'related'),
(77, 20, '92642', 'Hearing assistive device, supplemental technology fitting services (eg, personal FM/DM system, remote microphone, alerting devices)', 'CPT', 'related'),
(78, 20, 'S2230', 'Implantation of magnetic component of semi-implantable hearing device on ossicles in middle ear', 'HCPCS', 'covered'),
(79, 20, 'V5030', 'Hearing aid, monaural, body worn, air conduction', 'HCPCS', 'covered'),
(80, 20, 'V5050', 'Hearing aid, monaural, in the ear', 'HCPCS', 'covered'),
(81, 20, 'V5070', 'Glasses, air conduction', 'HCPCS', 'covered'),
(82, 20, 'V5095', 'Semi-implantable middle ear hearing prosthesis', 'HCPCS', 'covered'),
(83, 20, 'H90.3-H90.8', 'Sensorineural hearing loss and mixed conductive and sensorineural hearing loss', 'ICD-10', 'covered'),
(84, 20, 'Q16.1', 'Congenital absence, atresia and stricture of auditory canal (external)', 'ICD-10', 'covered'),
(85, 20, 'F32.0-F32.9','Major depressive disorder, single episode','ICD-10', 'not_covered'),
(86, 20, 'F33.0-F33.9','Major depressive disorder, recurrent','ICD-10', 'not_covered'),
(87, 20, 'H81.311-H81.399','Other peripheral vertigo','ICD-10', 'not_covered'),
(88, 20, 'H81.8X1-H81.8X9','Other disorders of vestibular function','ICD-10', 'not_covered'),
(89, 20, 'H81.90-H81.93','Unspecified disorder of vestibular function','ICD-10', 'not_covered'),
(90, 20, 'H82.1-H82.9','Vertiginous syndromes in diseases classified elsewhere','ICD-10', 'not_covered'),
(91, 20, 'R41.81','Age-related cognitive decline','ICD-10', 'not_covered');

-- Adalimumab
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(92,  7, '71045-71048', 'Radiologic examination, chest', 'CPT', 'related'),
(93,  7, '85651','Sedimentation rate, erythrocyte; non-automated', 'CPT', 'related'),
(94,  7, '85652','Sedimentation rate, erythrocyte; automated',  'CPT', 'related'),
(95,  7, '86140','C-reactive protein', 'CPT', 'related'),
(96,  7, '86141','C-reactive protein; high sensitivity (hsCRP)','CPT', 'related'),
(97,  7, '86200','Cyclic citrullinated peptide (CCP), antibody','CPT', 'related'),
(98,  7, '86430','Rheumatoid factor; qualitative','CPT', 'related'),
(99,  7, '86431','Rheumatoid factor; quantitative',  'CPT', 'related'),
(100, 7, '86480','Tuberculosis test, cell mediated immunity antigen response measurement; gamma interferon', 'CPT', 'related'),
(101, 7, '86481','Tuberculosis test, cell mediated immunity antigen response measurement; enumeration of gamma interferon-producing T cells', 'CPT', 'related'),
(102, 7, '86580','Skin test; tuberculosis, intradermal', 'CPT', 'related'),
(103, 7, '96372','Therapeutic, prophylactic, or diagnostic injection; subcutaneous or intramuscular', 'CPT', 'related'),
(104, 7, '96401-96450', 'Chemotherapy administration','CPT', 'related'),
(105, 7, 'J0139', 'Injection, adalimumab, 1 mg',  'HCPCS', 'covered'),
(106, 7, 'Q5140', 'Injection, adalimumab-fkjp, biosimilar, 1 mg',  'HCPCS', 'covered'),
(107, 7, 'Q5141', 'Injection, adalimumab-aaty, biosimilar, 1 mg',  'HCPCS', 'covered'),
(108, 7, 'Q5142', 'Injection, adalimumab-aaty, biosimilar, 1 mg',  'HCPCS', 'covered'),
(109, 7, 'Q5143', 'Injection, adalimumab-adbm, biosimilar, 1 mg',  'HCPCS', 'covered'),
(110, 7, 'Q5144', 'Injection, adalimumab-aacf (Idacio), biosimilar, 1 mg','HCPCS', 'covered'),
(111, 7, 'Q5145', 'Injection, adalimumab-afzb (Abrilada), biosimilar, 1 mg','HCPCS', 'covered'),
(112, 7, 'J0120','Injection, tetracycline, up to 250 mg','HCPCS', 'related'),
(113, 7, 'J0129','Injection, abatacept, 10 mg','HCPCS', 'related'),
(114, 7, 'J0702','Injection, betamethasone acetate 3 mg and betamethasone sodium phosphate 3 mg',  'HCPCS', 'related'),
(115, 7, 'J1094','Injection, dexamethasone acetate, 1 mg','HCPCS', 'related'),
(116, 7, 'J1100','Injection, dexamethasone sodium phosphate, 1 mg', 'HCPCS', 'related'),
(117, 7, 'J1130','Injection, diclofenac sodium, 0.5 mg', 'HCPCS', 'related'),
(118, 7, 'J1438','Injection, etanercept, 25 mg',  'HCPCS', 'related'),
(119, 7, 'J1600','Injection, gold sodium thiolamate, up to 50 mg',  'HCPCS', 'related'),
(120, 7, 'J1720','Injection, hydrocortisone sodium succinate, up to 100 mg',  'HCPCS', 'related'),
(121, 7, 'J1741','Injection, ibuprofen, 100 mg',  'HCPCS', 'related'),
(122, 7, 'J1745','Injection, infliximab, 10 mg',  'HCPCS', 'related'),
(123, 7, 'J1885','Injection, ketorolac tromethamine, per 15 mg','HCPCS', 'related'),
(124, 7, 'J2280','Injection, moxifloxacin, 100 mg','HCPCS', 'related'),
(125, 7, 'J2281','Injection, moxifloxacin (Fresenius Kabi), not therapeutically equivalent to J2280, 100 mg','HCPCS', 'related'),
(126, 7, 'J2650','Injection, prednisolone acetate, up to 1 ml', 'HCPCS', 'related'),
(127, 7, 'J2804','Injection, rifampin, 1 mg',  'HCPCS', 'related'),
(128, 7, 'J3245','Injection, tildrakizumab, 1 mg','HCPCS', 'related'),
(129, 7, 'J3300-J3301', 'Injection, triamcinolone acetonide','HCPCS', 'related'),
(130, 7, 'J3302','Injection, triamcinolone diacetate, per 5 mg','HCPCS', 'related'),
(131, 7, 'J3303','Injection, triamcinolone hexacetonide, per 5 mg', 'HCPCS', 'related'),
(132, 7, 'J7500','Azathioprine, oral, 50 mg',  'HCPCS', 'related'),
(133, 7, 'J7501','Azathioprine, parenteral, 100 mg',  'HCPCS', 'related'),
(134, 7, 'J7502','Cyclosporine, oral, 100 mg', 'HCPCS', 'related'),
(135, 7, 'J7510','Prednisolone, oral, per 5 mg',  'HCPCS', 'related'),
(136, 7, 'J7512','Prednisone, immediate release or delayed release, oral, 1 mg',  'HCPCS', 'related'),
(137, 7, 'J7515','Cyclosporine, oral, 25 mg',  'HCPCS', 'related'),
(138, 7, 'J7516','Cyclosporine, parenteral, 250 mg',  'HCPCS', 'related'),
(139, 7, 'J8530','Cyclophosphamide, oral, 25 mg', 'HCPCS', 'related'),
(140, 7, 'J8540','Injection, dexamethasone acetate, 1 mg','HCPCS', 'related'),
(141, 7, 'J8610','Methotrexate, oral, 2.5 mg', 'HCPCS', 'related'),
(142, 7, 'J8611','Methotrexate (Jylamvo), oral, 2.5 mg', 'HCPCS', 'related'),
(143, 7, 'J8612','Methotrexate (Xatmep), oral, 2.5 mg',  'HCPCS', 'related'),
(144, 7, 'J9070','Cyclophosphamide, 100 mg','HCPCS', 'related'),
(145, 7, 'J9073','Injection, cyclophosphamide (Ingenus), 5 mg', 'HCPCS', 'related'),
(146, 7, 'J9074','Injection, cyclophosphamide (Sandoz), 5 mg',  'HCPCS', 'related'),
(147, 7, 'J9075','Injection, cyclophosphamide, not otherwise specified, 5 mg','HCPCS', 'related'),
(148, 7, 'J9076','Injection, cyclophosphamide (Baxter), 5 mg',  'HCPCS', 'related'),
(149, 7, 'J9250','Methotrexate sodium, 5 mg',  'HCPCS', 'related'),
(150, 7, 'J9255','Injection, methotrexate (Accord), not therapeutically equivalent to J9250 or J9260, 50 mg','HCPCS', 'related'),
(151, 7, 'J9260','Methotrexate sodium, 50 mg', 'HCPCS', 'related'),
(152, 7, 'Q5109','Injection, infliximab-qbtx, biosimilar (Ixifi), 10 mg',  'HCPCS', 'related'),
(153, 7, 'S9359','Home infusion therapy, anti-tumor necrosis factor intravenous therapy (e.g., Infliximab); per diem',  'HCPCS', 'related');

-- PolicyCode for UnitedHealthcare - Habilitation and Rehabilitation Therapy
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(154, 26, '92507',  'Treatment of speech, language, voice, communication, and/or auditory processing disorder; individual', 'CPT', 'covered'),
(155, 26, '92508',  'Treatment of speech, language, voice, communication, and/or auditory processing disorder; group, 2 or more individuals', 'CPT', 'covered'),
(156, 26, '92521',  'Evaluation of speech fluency (e.g., stuttering, cluttering)', 'CPT', 'covered'),
(157, 26, '92522',  'Evaluation of speech sound production (e.g., articulation, phonological process, apraxia, dysarthria)', 'CPT', 'covered'),
(158, 26, '92523',  'Evaluation of speech sound production with evaluation of language comprehension and expression', 'CPT', 'covered'),
(159, 26, '92524',  'Behavioral and qualitative analysis of voice and resonance', 'CPT', 'covered'),
(160, 26, '92526',  'Treatment of swallowing dysfunction and/or oral function for feeding', 'CPT', 'covered'),
(161, 26, '92609',  'Therapeutic services for the use of speech-generating device, including programming and modification', 'CPT', 'covered'),
(162, 26, '92610',  'Evaluation of oral and pharyngeal swallowing function', 'CPT', 'covered'),
(163, 26, '96105',  'Assessment of aphasia with interpretation and report, per hour', 'CPT', 'covered'),
(164, 26, '97012',  'Application of a modality to 1 or more areas; traction, mechanical', 'CPT', 'covered'),
(165, 26, '97014',  'Application of a modality to 1 or more areas; electrical stimulation (unattended)', 'CPT', 'covered'),
(166, 26, '97016',  'Application of a modality to 1 or more areas; vasopneumatic devices', 'CPT', 'covered'),
(167, 26, '97018',  'Application of a modality to 1 or more areas; paraffin bath', 'CPT', 'covered'),
(168, 26, '97022',  'Application of a modality to 1 or more areas; whirlpool', 'CPT', 'covered'),
(169, 26, '97024',  'Application of a modality to 1 or more areas; diathermy (e.g., microwave)', 'CPT', 'covered'),
(170, 26, '97026',  'Application of a modality to 1 or more areas; infrared', 'CPT', 'covered'),
(171, 26, '97028',  'Application of a modality to 1 or more areas; ultraviolet', 'CPT', 'covered'),
(172, 26, '97032',  'Application of a modality to 1 or more areas; electrical stimulation (manual), each 15 minutes', 'CPT', 'covered'),
(173, 26, '97033',  'Application of a modality to 1 or more areas; iontophoresis, each 15 minutes', 'CPT', 'covered'),
(174, 26, '97034',  'Application of a modality to 1 or more areas; contrast baths, each 15 minutes', 'CPT', 'covered'),
(175, 26, '97035',  'Application of a modality to 1 or more areas; ultrasound, each 15 minutes', 'CPT', 'covered'),
(176, 26, '97036',  'Application of a modality to 1 or more areas; Hubbard tank, each 15 minutes', 'CPT', 'covered'),
(177, 26, '97039',  'Unlisted modality (specify type and time if constant attendance)', 'CPT', 'covered'),
(178, 26, '97110',  'Therapeutic exercises to develop strength and endurance, range of motion and flexibility, each 15 minutes', 'CPT', 'covered'),
(179, 26, '97112',  'Neuromuscular reeducation of movement, balance, coordination, posture, and/or proprioception, each 15 minutes', 'CPT', 'covered'),
(180, 26, '97113',  'Aquatic therapy with therapeutic exercises, each 15 minutes', 'CPT', 'covered'),
(181, 26, '97116',  'Gait training (includes stair climbing), each 15 minutes', 'CPT', 'covered'),
(182, 26, '97139',  'Unlisted therapeutic procedure (specify)', 'CPT', 'covered'),
(183, 26, '97140',  'Manual therapy techniques (e.g., mobilization/manipulation, manual traction), each 15 minutes', 'CPT', 'covered'),
(184, 26, '97150',  'Therapeutic procedure(s), group (2 or more individuals)', 'CPT', 'covered'),
(185, 26, '97161',  'Physical therapy evaluation: low complexity', 'CPT', 'covered'),
(186, 26, '97162',  'Physical therapy evaluation: moderate complexity', 'CPT', 'covered'),
(187, 26, '97163',  'Physical therapy evaluation: high complexity', 'CPT', 'covered'),
(188, 26, '97164',  'Re-evaluation of physical therapy established plan of care', 'CPT', 'covered'),
(189, 26, '97165',  'Occupational therapy evaluation: low complexity', 'CPT', 'covered'),
(190, 26, '97166',  'Occupational therapy evaluation: moderate complexity', 'CPT', 'covered'),
(191, 26, '97167',  'Occupational therapy evaluation: high complexity', 'CPT', 'covered'),
(192, 26, '97168',  'Re-evaluation of occupational therapy established plan of care', 'CPT', 'covered'),
(193, 26, '97530',  'Therapeutic activities, direct one-on-one patient contact, each 15 minutes', 'CPT', 'covered'),
(194, 26, '97535',  'Self-care/home management training (ADL and compensatory training), each 15 minutes', 'CPT', 'covered'),
(195, 26, '97542',  'Wheelchair management (assessment, fitting, training), each 15 minutes', 'CPT', 'covered'),
(196, 26, '97750',  'Physical performance test or measurement (e.g., musculoskeletal, functional capacity), each 15 minutes', 'CPT', 'covered'),
(197, 26, '97755',  'Assistive technology assessment, direct one-on-one contact, with written report, each 15 minutes', 'CPT', 'covered'),
(198, 26, '97760',  'Orthotic(s) management and training, upper/lower extremity(ies) and/or trunk, initial encounter, each 15 minutes', 'CPT', 'covered'),
(199, 26, '97761',  'Prosthetic(s) training, upper and/or lower extremity(ies), initial encounter, each 15 minutes', 'CPT', 'covered'),
(200, 26, '97763',  'Orthotic(s)/prosthetic(s) management and/or training, subsequent encounter, each 15 minutes', 'CPT', 'covered'),
(201, 26, '97799',  'Unlisted physical medicine/rehabilitation service or procedure', 'CPT', 'covered'),
(202, 26, 'G0281',  'Electrical stimulation (unattended) for chronic Stage III/IV pressure, arterial, diabetic, or venous stasis ulcers', 'HCPCS', 'covered'),
(203, 26, 'G0283',  'Electrical stimulation (unattended) to one or more areas for indications other than wound care', 'HCPCS', 'covered'),
(204, 26, 'S8948',  'Application of low-level laser modality (requiring constant provider attendance), each 15 minutes', 'HCPCS', 'covered'),
(205, 26, 'S8990',  'Physical or manipulative therapy performed for maintenance rather than restoration', 'HCPCS', 'covered'),
(206, 26, 'S9129',  'Occupational therapy, in the home, per diem', 'HCPCS', 'covered'),
(207, 26, 'S9131',  'Physical therapy, in the home, per diem', 'HCPCS', 'covered'),
(208, 26, 'S9152',  'Speech therapy, re-evaluation', 'HCPCS', 'covered');

-- PolicyCode for Humana - Outpatient Rehabilitation (Physical Therapy, Occupational Therapy)
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(209, 25, '20999',  'Unlisted procedure, musculoskeletal system, general', 'CPT', 'covered'),
(210, 25, '29200',  'Strapping; thorax', 'CPT', 'covered'),
(211, 25, '29240',  'Strapping; shoulder (eg, Velpeau)', 'CPT', 'covered'),
(212, 25, '29260',  'Strapping; elbow or wrist', 'CPT', 'covered'),
(213, 25, '29280',  'Strapping; hand or finger', 'CPT', 'covered'),
(214, 25, '29520',  'Strapping; hip', 'CPT', 'covered'),
(215, 25, '29530',  'Strapping; knee', 'CPT', 'covered'),
(216, 25, '29540',  'Strapping; ankle and/or foot', 'CPT', 'covered'),
(217, 25, '29550',  'Strapping; toes', 'CPT', 'covered'),
(218, 25, '29799',  'Unlisted procedure, casting or strapping', 'CPT', 'covered'),
(219, 25, '96000',  'Comprehensive computer-based motion analysis by videotaping and 3D kinematics', 'CPT', 'covered'),
(220, 25, '96001',  'Comprehensive computer-based motion analysis with dynamic plantar pressure measurements during walking', 'CPT', 'covered'),
(221, 25, '96004',  'Review and interpretation of comprehensive computer-based motion analysis, with written report', 'CPT', 'covered'),
(222, 25, '97010',  'Application of a modality to 1 or more areas; hot or cold packs', 'CPT', 'covered'),
(223, 25, '97012',  'Application of a modality to 1 or more areas; traction, mechanical', 'CPT', 'covered'),
(224, 25, '97014',  'Application of a modality to 1 or more areas; electrical stimulation (unattended)', 'CPT', 'covered'),
(225, 25, '97016',  'Application of a modality to 1 or more areas; vasopneumatic devices', 'CPT', 'covered'),
(226, 25, '97018',  'Application of a modality to 1 or more areas; paraffin bath', 'CPT', 'covered'),
(227, 25, '97022',  'Application of a modality to 1 or more areas; whirlpool', 'CPT', 'covered'),
(228, 25, '97024',  'Application of a modality to 1 or more areas; diathermy (eg, microwave)', 'CPT', 'covered'),
(229, 25, '97026',  'Application of a modality to 1 or more areas; infrared', 'CPT', 'covered'),
(230, 25, '97028',  'Application of a modality to 1 or more areas; ultraviolet', 'CPT', 'covered'),
(231, 25, '97032',  'Application of a modality to 1 or more areas; electrical stimulation (manual), each 15 minutes', 'CPT', 'covered'),
(232, 25, '97033',  'Application of a modality to 1 or more areas; iontophoresis, each 15 minutes', 'CPT', 'covered'),
(233, 25, '97034',  'Application of a modality to 1 or more areas; contrast baths, each 15 minutes', 'CPT', 'covered'),
(234, 25, '97035',  'Application of a modality to 1 or more areas; ultrasound, each 15 minutes', 'CPT', 'covered'),
(235, 25, '97036',  'Application of a modality to 1 or more areas; Hubbard tank, each 15 minutes', 'CPT', 'covered'),
(236, 25, '97037',  'Application of a modality to 1 or more areas; low-level laser therapy (nonthermal, non-ablative) for post-operative pain reduction', 'CPT', 'not_covered'),
(237, 25, '97039',  'Unlisted modality — billed for high power laser therapy; not considered medically necessary', 'CPT', 'not_covered'),
(238, 25, '97110',  'Therapeutic exercises to develop strength and endurance, range of motion and flexibility, each 15 minutes', 'CPT', 'covered'),
(239, 25, '97112',  'Neuromuscular reeducation of movement, balance, coordination, posture, and/or proprioception, each 15 minutes', 'CPT', 'covered'),
(240, 25, '97113',  'Aquatic therapy with therapeutic exercises, each 15 minutes', 'CPT', 'covered'),
(241, 25, '97116',  'Gait training (includes stair climbing), each 15 minutes', 'CPT', 'covered'),
(242, 25, '97124',  'Massage, including effleurage, petrissage and/or tapotement, each 15 minutes', 'CPT', 'covered'),
(243, 25, '97129',  'Therapeutic interventions focusing on cognitive function and compensatory strategies; initial 15 minutes', 'CPT', 'covered'),
(244, 25, '97130',  'Therapeutic interventions focusing on cognitive function and compensatory strategies; each additional 15 minutes', 'CPT', 'covered'),
(245, 25, '97139',  'Unlisted therapeutic procedure (specify)', 'CPT', 'covered'),
(246, 25, '97140',  'Manual therapy techniques (eg, mobilization/manipulation, manual traction), each 15 minutes', 'CPT', 'covered'),
(247, 25, '97150',  'Therapeutic procedure(s), group (2 or more individuals)', 'CPT', 'covered'),
(248, 25, '97161',  'Physical therapy evaluation: low complexity', 'CPT', 'covered'),
(249, 25, '97162',  'Physical therapy evaluation: moderate complexity', 'CPT', 'covered'),
(250, 25, '97163',  'Physical therapy evaluation: high complexity', 'CPT', 'covered'),
(251, 25, '97164',  'Re-evaluation of physical therapy established plan of care', 'CPT', 'covered'),
(252, 25, '97165',  'Occupational therapy evaluation: low complexity', 'CPT', 'covered'),
(253, 25, '97166',  'Occupational therapy evaluation: moderate complexity', 'CPT', 'covered'),
(254, 25, '97167',  'Occupational therapy evaluation: high complexity', 'CPT', 'covered'),
(255, 25, '97168',  'Re-evaluation of occupational therapy established plan of care', 'CPT', 'covered'),
(256, 25, '97530',  'Therapeutic activities, direct one-on-one patient contact, each 15 minutes', 'CPT', 'covered'),
(257, 25, '97533',  'Sensory integrative techniques to enhance sensory processing and promote adaptive responses, each 15 minutes', 'CPT', 'covered'),
(258, 25, '97535',  'Self-care/home management training (ADL and compensatory training), each 15 minutes', 'CPT', 'covered'),
(259, 25, '97537',  'Community/work reintegration training (shopping, transportation, money management), each 15 minutes', 'CPT', 'covered'),
(260, 25, '97542',  'Wheelchair management (assessment, fitting, training), each 15 minutes', 'CPT', 'covered'),
(261, 25, '97545',  'Work hardening/conditioning; initial 2 hours', 'CPT', 'covered'),
(262, 25, '97546',  'Work hardening/conditioning; each additional hour', 'CPT', 'covered'),
(263, 25, '97550',  'Caregiver training in strategies to facilitate patient functional performance; initial 30 minutes', 'CPT', 'covered'),
(264, 25, '97551',  'Caregiver training in strategies to facilitate patient functional performance; each additional 15 minutes', 'CPT', 'covered'),
(265, 25, '97552',  'Group caregiver training in strategies to facilitate patient functional performance', 'CPT', 'covered'),
(266, 25, '97750',  'Physical performance test or measurement (eg, musculoskeletal, functional capacity), each 15 minutes', 'CPT', 'covered'),
(267, 25, '97755',  'Assistive technology assessment, direct one-on-one contact, with written report, each 15 minutes', 'CPT', 'covered'),
(268, 25, '97760',  'Orthotic(s) management and training, upper/lower extremity(ies) and/or trunk, initial encounter, each 15 minutes', 'CPT', 'covered'),
(269, 25, '97761',  'Prosthetic(s) training, upper and/or lower extremity(ies), initial encounter, each 15 minutes', 'CPT', 'covered'),
(270, 25, '97763',  'Orthotic(s)/prosthetic(s) management and/or training, subsequent encounter, each 15 minutes', 'CPT', 'covered'),
(271, 25, '97799',  'Unlisted physical medicine/rehabilitation service or procedure', 'CPT', 'covered'),
(272, 25, '0552T',  'Low-level laser therapy, dynamic photonic and dynamic thermokinetic energies; not medically necessary per Humana', 'CPT', 'not_covered'),
(273, 25, '0733T',  'Remote body and limb kinematic measurement-based therapy; supply and technical support, per 30 days', 'CPT', 'covered'),
(274, 25, '0734T',  'Remote body and limb kinematic measurement-based therapy; treatment management services, per calendar month', 'CPT', 'covered'),
(275, 25, '0791T',  'Motor-cognitive, semi-immersive virtual reality-facilitated gait training, each 15 minutes', 'CPT', 'covered'),
(276, 25, 'G0129',  'Occupational therapy services in a partial hospitalization treatment program, per session (45 min or more)', 'HCPCS', 'covered'),
(277, 25, 'G0281',  'Electrical stimulation (unattended) for chronic Stage III/IV pressure, arterial, diabetic, or venous stasis ulcers', 'HCPCS', 'covered'),
(278, 25, 'G0282',  'Electrical stimulation (unattended) for wound care other than described in G0281', 'HCPCS', 'covered'),
(279, 25, 'G0283',  'Electrical stimulation (unattended) to one or more areas for indications other than wound care', 'HCPCS', 'covered');


-- PolicyCode for Cigna - Therapy Services Physical Therapy (CPG 135)
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(280, 24, '94667',  'Manipulation chest wall (cupping, percussing, vibration) to facilitate lung function; initial demonstration and/or evaluation', 'CPT', 'covered'),
(281, 24, '94668',  'Manipulation chest wall (cupping, percussing, vibration) to facilitate lung function; subsequent', 'CPT', 'covered'),
(282, 24, '97010',  'Application of a modality to 1 or more areas; hot or cold packs', 'CPT', 'covered'),
(283, 24, '97012',  'Application of a modality to 1 or more areas; traction, mechanical', 'CPT', 'covered'),
(284, 24, '97014',  'Application of a modality to 1 or more areas; electrical stimulation (unattended)', 'CPT', 'covered'),
(285, 24, '97018',  'Application of a modality to 1 or more areas; paraffin bath', 'CPT', 'covered'),
(286, 24, '97022',  'Application of a modality to 1 or more areas; whirlpool', 'CPT', 'covered'),
(287, 24, '97024',  'Application of a modality to 1 or more areas; diathermy (eg, microwave)', 'CPT', 'covered'),
(288, 24, '97028',  'Application of a modality to 1 or more areas; ultraviolet', 'CPT', 'covered'),
(289, 24, '97032',  'Application of a modality to 1 or more areas; electrical stimulation (manual), each 15 minutes', 'CPT', 'covered'),
(290, 24, '97033',  'Application of a modality to 1 or more areas; iontophoresis, each 15 minutes', 'CPT', 'covered'),
(291, 24, '97034',  'Application of a modality to 1 or more areas; contrast baths, each 15 minutes', 'CPT', 'covered'),
(292, 24, '97035',  'Application of a modality to 1 or more areas; ultrasound, each 15 minutes', 'CPT', 'covered'),
(293, 24, '97036',  'Application of a modality to 1 or more areas; Hubbard tank, each 15 minutes', 'CPT', 'covered'),
(294, 24, '97110',  'Therapeutic exercises to develop strength and endurance, range of motion and flexibility, each 15 minutes', 'CPT', 'covered'),
(295, 24, '97112',  'Neuromuscular reeducation of movement, balance, coordination, posture, and/or proprioception, each 15 minutes', 'CPT', 'covered'),
(296, 24, '97113',  'Aquatic therapy with therapeutic exercises, each 15 minutes', 'CPT', 'covered'),
(297, 24, '97116',  'Gait training (includes stair climbing), each 15 minutes', 'CPT', 'covered'),
(298, 24, '97124',  'Massage, including effleurage, petrissage and/or tapotement, each 15 minutes', 'CPT', 'covered'),
(299, 24, '97140',  'Manual therapy techniques (eg, mobilization/manipulation, manual traction), each 15 minutes', 'CPT', 'covered'),
(300, 24, '97150',  'Therapeutic procedure(s), group (2 or more individuals)', 'CPT', 'covered'),
(301, 24, '97161',  'Physical therapy evaluation: low complexity', 'CPT', 'covered'),
(302, 24, '97162',  'Physical therapy evaluation: moderate complexity', 'CPT', 'covered'),
(303, 24, '97163',  'Physical therapy evaluation: high complexity', 'CPT', 'covered'),
(304, 24, '97164',  'Re-evaluation of physical therapy established plan of care', 'CPT', 'covered'),
(305, 24, '97530',  'Therapeutic activities, direct one-on-one patient contact, each 15 minutes', 'CPT', 'covered'),
(306, 24, '97535',  'Self-care/home management training (ADL and compensatory training), each 15 minutes', 'CPT', 'covered'),
(307, 24, '97542',  'Wheelchair management (assessment, fitting, training), each 15 minutes', 'CPT', 'covered'),
(308, 24, '97760',  'Orthotic(s) management and training, upper/lower extremity(ies) and/or trunk, initial encounter, each 15 minutes', 'CPT', 'covered'),
(309, 24, '97761',  'Prosthetic(s) training, upper and/or lower extremity(ies), initial encounter, each 15 minutes', 'CPT', 'covered'),
(310, 24, '97763',  'Orthotic(s)/prosthetic(s) management and/or training, subsequent encounter, each 15 minutes', 'CPT', 'covered'),
(311, 24, 'G0151',  'Services performed by a qualified physical therapist in the home health or hospice setting, each 15 minutes', 'HCPCS', 'covered'),
(312, 24, 'G0237',  'Therapeutic procedures to increase strength or endurance of respiratory muscles, face to face, each 15 minutes', 'HCPCS', 'covered'),
(313, 24, 'G0238',  'Therapeutic procedures to improve respiratory function, other than G0237, face to face, per 15 minutes', 'HCPCS', 'covered'),
(314, 24, 'G0239',  'Therapeutic procedures to improve respiratory function or increase strength of respiratory muscles, 2 or more individuals', 'HCPCS', 'covered'),
(315, 24, 'S9131',  'Physical therapy, in the home, per diem', 'HCPCS', 'covered'),
(316, 24, 'L3763',  'Elbow wrist hand orthosis, rigid, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(317, 24, 'L3764',  'Elbow wrist hand orthosis, includes nontorsion joints, elastic bands, turnbuckles, custom fabricated', 'HCPCS', 'covered'),
(318, 24, 'L3765',  'Elbow wrist hand finger orthosis, rigid, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(319, 24, 'L3766',  'Elbow wrist hand finger orthosis, includes non-torsion joints, elastic bands, turnbuckles, custom fabricated', 'HCPCS', 'covered'),
(320, 24, 'L3806',  'Wrist hand finger orthosis, includes nontorsion joints, turnbuckles, elastic bands/springs, custom fabricated', 'HCPCS', 'covered'),
(321, 24, 'L3807',  'Wrist hand finger orthosis without joints, prefabricated, customized to fit a specific patient', 'HCPCS', 'covered'),
(322, 24, 'L3808',  'Wrist hand finger orthosis, rigid without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(323, 24, 'L3891',  'Addition to upper extremity joint, wrist or elbow, concentric adjustable torsion mechanism, custom fabricated orthotics only', 'HCPCS', 'covered'),
(324, 24, 'L3900',  'Wrist hand finger orthosis, dynamic flexor hinge, reciprocal wrist/finger extension/flexion, wrist or finger driven, custom fabricated', 'HCPCS', 'covered'),
(325, 24, 'L3901',  'Wrist hand finger orthosis, dynamic flexor hinge, reciprocal wrist/finger extension/flexion, cable driven, custom fabricated', 'HCPCS', 'covered'),
(326, 24, 'L3905',  'Wrist hand orthosis, includes nontorsion joints, elastic bands, turnbuckles, custom fabricated', 'HCPCS', 'covered'),
(327, 24, 'L3906',  'Wrist hand orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(328, 24, 'L3913',  'Hand finger orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(329, 24, 'L3915',  'Wrist hand orthosis, includes nontorsion joints, elastic bands, turnbuckles, prefabricated, customized', 'HCPCS', 'covered'),
(330, 24, 'L3917',  'Hand orthosis, metacarpal fracture orthosis, prefabricated, customized to fit a specific patient', 'HCPCS', 'covered'),
(331, 24, 'L3919',  'Hand orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(332, 24, 'L3921',  'Hand finger orthosis, includes nontorsion joints, elastic bands, turnbuckles, custom fabricated', 'HCPCS', 'covered'),
(333, 24, 'L3923',  'Hand finger orthosis, without joints, prefabricated, customized to fit a specific patient', 'HCPCS', 'covered'),
(334, 24, 'L3929',  'Hand finger orthosis, includes nontorsion joints, turnbuckles, elastic bands/springs, prefabricated, customized', 'HCPCS', 'covered'),
(335, 24, 'L3931',  'Wrist hand finger orthosis, includes nontorsion joints, turnbuckles, elastic bands/springs, prefabricated', 'HCPCS', 'covered'),
(336, 24, 'L3933',  'Finger orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(337, 24, 'L3935',  'Finger orthosis, nontorsion joint, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(338, 24, 'L3956',  'Addition of joint to upper extremity orthosis, any material, per joint', 'HCPCS', 'covered'),
(339, 24, 'L4205',  'Repair of orthotic device, labor component, per 15 minutes', 'HCPCS', 'covered'),
(340, 24, '97016',  'Application of a modality to 1 or more areas; vasopneumatic devices — not medically necessary per Cigna', 'CPT', 'not_covered'),
(341, 24, '97026',  'Application of a modality to 1 or more areas; infrared — not medically necessary per Cigna', 'CPT', 'not_covered'),
(342, 24, '97169',  'Athletic training evaluation, low complexity', 'CPT', 'not_covered'),
(343, 24, '97170',  'Athletic training evaluation, moderate complexity', 'CPT', 'not_covered'),
(344, 24, '97171',  'Athletic training evaluation, high complexity', 'CPT', 'not_covered'),
(345, 24, '97172',  'Re-evaluation of athletic training established plan of care', 'CPT', 'not_covered'),
(346, 24, '97537',  'Community/work reintegration training — educational/vocational in nature, not medically necessary', 'CPT', 'not_covered'),
(347, 24, '97545',  'Work hardening/conditioning; initial 2 hours — not medically necessary per Cigna', 'CPT', 'not_covered'),
(348, 24, '97546',  'Work hardening/conditioning; each additional hour — not medically necessary per Cigna', 'CPT', 'not_covered'),
(349, 24, 'S8990',  'Physical or manipulative therapy for maintenance rather than restoration — not medically necessary', 'HCPCS', 'not_covered'),
(350, 24, 'S9117',  'Back school, per visit — not medically necessary per Cigna', 'HCPCS', 'not_covered'),
(351, 24, '20560',  'Needle insertion(s) without injection(s); 1 or 2 muscle(s) — dry needling, considered experimental', 'CPT', 'not_covered'),
(352, 24, '20561',  'Needle insertion(s) without injection(s); 3 or more muscles — dry needling, considered experimental', 'CPT', 'not_covered'),
(353, 24, '97610',  'Low frequency, non-contact, non-thermal ultrasound, including topical application(s), per day — experimental', 'CPT', 'not_covered'),
(354, 24, '97039',  'Unlisted modality — when used for experimental treatments listed in policy (eg, MENS, H-WAVE, InterX)', 'CPT', 'not_covered'),
(355, 24, '97799',  'Unlisted physical medicine/rehabilitation service — when used for experimental treatments listed in policy', 'CPT', 'not_covered'),
(356, 24, 'S8940',  'Equestrian/hippotherapy, per session — experimental per Cigna', 'HCPCS', 'not_covered'),
(357, 24, 'S9090',  'Vertebral axial decompression, per session — experimental per Cigna', 'HCPCS', 'not_covered');

-- Cigna Hearing Aids (PolicyCoverageID=27, Policy 0093, Effective 6/15/2025)
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(358, 27, 'V5030', 'Hearing aid, monaural, body worn, air conduction', 'HCPCS', 'covered'),
(359, 27, 'V5040', 'Hearing aid, monaural, body worn, bone conduction', 'HCPCS', 'covered'),
(360, 27, 'V5050', 'Hearing aid, monaural, in the ear', 'HCPCS', 'covered'),
(361, 27, 'V5060', 'Hearing aid, monaural, behind the ear', 'HCPCS', 'covered'),
(362, 27, 'V5100', 'Hearing aid, bilateral, body worn', 'HCPCS', 'covered'),
(363, 27, 'V5120', 'Binaural hearing aid, body worn', 'HCPCS', 'covered'),
(364, 27, 'V5130', 'Binaural hearing aid, in the ear', 'HCPCS', 'covered'),
(365, 27, 'V5140', 'Binaural hearing aid, behind the ear', 'HCPCS', 'covered'),
(366, 27, 'V5171', 'Hearing aid, CROS/BiCROS, monaural, in the ear (ITE)', 'HCPCS', 'covered'),
(367, 27, 'V5172', 'Hearing aid, CROS/BiCROS, monaural, behind the ear (BTE)', 'HCPCS', 'covered'),
(368, 27, 'V5181', 'Hearing aid, CROS/BiCROS, binaural, in the ear (ITE)', 'HCPCS', 'covered'),
(369, 27, 'V5211', 'Hearing aid, disposable, any type, monaural', 'HCPCS', 'covered'),
(370, 27, 'V5212', 'Hearing aid, disposable, any type, binaural', 'HCPCS', 'covered'),
(371, 27, 'V5213', 'Hearing aid, digitally programmable analog, monaural, CIC or canal', 'HCPCS', 'covered'),
(372, 27, 'V5214', 'Hearing aid, digitally programmable analog, monaural, ITE', 'HCPCS', 'covered'),
(373, 27, 'V5215', 'Hearing aid, digitally programmable analog, monaural, BTE', 'HCPCS', 'covered'),
(374, 27, 'V5221', 'Hearing aid, digitally programmable analog, binaural, CIC or canal', 'HCPCS', 'covered'),
(375, 27, 'V5242', 'Hearing aid, digitally programmable, binaural, CIC or canal', 'HCPCS', 'covered'),
(376, 27, 'V5243', 'Hearing aid, digitally programmable, binaural, ITE', 'HCPCS', 'covered'),
(377, 27, 'V5244', 'Hearing aid, digitally programmable, monaural, CIC or canal', 'HCPCS', 'covered'),
(378, 27, 'V5245', 'Hearing aid, digitally programmable, monaural, ITE', 'HCPCS', 'covered'),
(379, 27, 'V5246', 'Hearing aid, digitally programmable, monaural, BTE', 'HCPCS', 'covered'),
(380, 27, 'V5247', 'Hearing aid, digitally programmable, binaural, BTE', 'HCPCS', 'covered'),
(381, 27, 'V5248', 'Hearing aid, analog, monaural, CIC or canal', 'HCPCS', 'covered'),
(382, 27, 'V5249', 'Hearing aid, analog, monaural, ITE', 'HCPCS', 'covered'),
(383, 27, 'V5250', 'Hearing aid, monaural, canal', 'HCPCS', 'covered'),
(384, 27, 'V5251', 'Hearing aid, monaural, canal, programmable', 'HCPCS', 'covered'),
(385, 27, 'V5252', 'Hearing aid, monaural, CIC', 'HCPCS', 'covered'),
(386, 27, 'V5253', 'Hearing aid, monaural, CIC, programmable', 'HCPCS', 'covered'),
(387, 27, 'V5254', 'Hearing aid, monaural, ITE', 'HCPCS', 'covered'),
(388, 27, 'V5255', 'Hearing aid, monaural, ITE, programmable', 'HCPCS', 'covered'),
(389, 27, 'V5256', 'Hearing aid, monaural, BTE', 'HCPCS', 'covered'),
(390, 27, 'V5257', 'Hearing aid, monaural, BTE, programmable', 'HCPCS', 'covered'),
(391, 27, 'V5258', 'Hearing aid, monaural, open fit, BTE', 'HCPCS', 'covered'),
(392, 27, 'V5259', 'Hearing aid, binaural, open fit, BTE', 'HCPCS', 'covered'),
(393, 27, 'V5260', 'Hearing aid, binaural, canal', 'HCPCS', 'covered'),
(394, 27, 'V5261', 'Hearing aid, binaural, canal, programmable', 'HCPCS', 'covered'),
(395, 27, 'V5262', 'Hearing aid, binaural, CIC', 'HCPCS', 'covered'),
(396, 27, 'V5263', 'Hearing aid, binaural, CIC, programmable', 'HCPCS', 'covered'),
(397, 27, 'V5264', 'Hearing aid, binaural, ITE', 'HCPCS', 'covered'),
(398, 27, 'V5265', 'Hearing aid, binaural, ITE, programmable', 'HCPCS', 'covered'),
(399, 27, 'V5267', 'Hearing aid, CROS/BiCROS, binaural, CIC', 'HCPCS', 'covered'),
(400, 27, 'V5275', 'Hearing aid, wireless, binaural, any type', 'HCPCS', 'covered'),
(401, 27, '69799', 'Unlisted procedure, middle ear', 'CPT', 'covered'),
(402, 27, 'S2230', 'Implantable cochlear prosthesis, partially implantable bone conduction hearing device', 'HCPCS', 'covered'),
(403, 27, 'V5095', 'Semi-implantable middle ear hearing prosthesis', 'HCPCS', 'covered'),
(404, 27, '69710', 'Implantation or replacement of electromagnetic bone conduction hearing device in temporal bone', 'CPT', 'covered'),
(405, 27, '69714', 'Implantation, osseointegrated implant, temporal bone, with percutaneous attachment to external speech processor, without mastoidectomy', 'CPT', 'covered'),
(406, 27, '69716', 'Implantation, osseointegrated implant, temporal bone, with transcutaneous magnetic attachment to external speech processor, without mastoidectomy', 'CPT', 'covered'),
(407, 27, '69729', 'Implantation or replacement of bone anchored hearing aid, osseointegrated implant, external speech processor', 'CPT', 'covered'),
(408, 27, 'L8690', 'Auditory osseointegrated device, includes all internal and external components', 'HCPCS', 'covered'),
(409, 27, 'L8692', 'Auditory osseointegrated device, replacement external speech processor, includes transmitter coil', 'HCPCS', 'covered'),
(410, 27, 'V5266', 'Battery for use in hearing device', 'HCPCS', 'covered'),
(411, 27, 'L8621', 'Zinc air battery, hearing instrument, per battery', 'HCPCS', 'covered'),
(412, 27, 'L8622', 'Alkaline battery, hearing instrument, per battery', 'HCPCS', 'covered'),
(413, 27, 'L8623', 'Lithium ion battery, hearing instrument, rechargeable', 'HCPCS', 'covered'),
(414, 27, 'L8624', 'Lithium ion battery charger, hearing instrument', 'HCPCS', 'covered'),
(415, 27, '69711', 'Removal or repair of electromagnetic bone conduction hearing device in temporal bone', 'CPT', 'covered'),
(416, 27, '69717', 'Replacement of osseointegrated implant, temporal bone, with percutaneous attachment, without mastoidectomy', 'CPT', 'covered'),
(417, 27, '69719', 'Replacement of osseointegrated implant, temporal bone, with transcutaneous magnetic attachment, without mastoidectomy', 'CPT', 'covered'),
(418, 27, '69730', 'Removal or replacement of bone anchored hearing aid, osseointegrated implant, external speech processor', 'CPT', 'covered'),
(419, 27, '69399', 'Unlisted procedure, external ear', 'CPT', 'covered'),
(420, 27, 'L8618', 'Cochlear implant, external speech processor, replacement', 'HCPCS', 'covered'),
(421, 27, 'L8625', 'Osseointegrated implant abutment, replacement, includes attachment plate or cradle and screw', 'HCPCS', 'covered'),
(422, 27, 'L8691', 'Auditory osseointegrated device, external sound processor, used with osseointegrated implant', 'HCPCS', 'covered'),
(423, 27, 'L8693', 'Auditory osseointegrated device, external sound processor, replacement', 'HCPCS', 'covered'),
(424, 27, 'L8694', 'Auditory osseointegrated device, osseointegrated implant, replacement', 'HCPCS', 'covered'),
(425, 27, 'L9900', 'Orthotic or prosthetic item, not otherwise specified (hearing aid repair/replacement)', 'HCPCS', 'covered'),
(426, 27, 'V5014', 'Repair or modification of a hearing aid', 'HCPCS', 'covered'),
(427, 27, '0951T', 'Percutaneous implantation or replacement of aural pressure sensor for wireless ambulatory intracranial pressure monitoring', 'CPT', 'not_covered'),
(428, 27, 'V5298', 'Not otherwise classified, hearing aid related service', 'HCPCS', 'not_covered');

-- Aetna Physical Therapy (PolicyCoverageID=23, CPB 0325)
INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(429, 23, '97010', 'Application of a modality to 1 or more areas, hot or cold packs', 'CPT', 'covered'),
(430, 23, '97012', 'Application of a modality to 1 or more areas, traction, mechanical', 'CPT', 'covered'),
(431, 23, '97014', 'Application of a modality to 1 or more areas, electrical stimulation (unattended)', 'CPT', 'covered'),
(432, 23, '97016', 'Application of a modality to 1 or more areas, vasopneumatic devices', 'CPT', 'covered'),
(433, 23, '97018', 'Application of a modality to 1 or more areas, paraffin bath', 'CPT', 'covered'),
(434, 23, '97022', 'Application of a modality to 1 or more areas, whirlpool', 'CPT', 'covered'),
(435, 23, '97024', 'Application of a modality to 1 or more areas, diathermy (eg, microwave)', 'CPT', 'covered'),
(436, 23, '97026', 'Application of a modality to 1 or more areas, infrared', 'CPT', 'covered'),
(437, 23, '97028', 'Application of a modality to 1 or more areas, ultraviolet', 'CPT', 'covered'),
(438, 23, '97032', 'Application of a modality to one or more areas, electrical stimulation (manual), each 15 minutes', 'CPT', 'covered'),
(439, 23, '97033', 'Application of a modality to one or more areas, iontophoresis, each 15 minutes', 'CPT', 'covered'),
(440, 23, '97034', 'Application of a modality to one or more areas, contrast baths, each 15 minutes', 'CPT', 'covered'),
(441, 23, '97035', 'Application of a modality to one or more areas, ultrasound, each 15 minutes', 'CPT', 'covered'),
(442, 23, '97036', 'Application of a modality to one or more areas, Hubbard tank, each 15 minutes', 'CPT', 'covered'),
(443, 23, '97110', 'Therapeutic exercises to develop strength and endurance, range of motion and flexibility, each 15 minutes', 'CPT', 'covered'),
(444, 23, '97112', 'Neuromuscular reeducation of movement, balance, coordination, kinesthetic sense, posture, and/or proprioception, each 15 minutes', 'CPT', 'covered'),
(445, 23, '97113', 'Aquatic therapy with therapeutic exercise, each 15 minutes', 'CPT', 'covered'),
(446, 23, '97116', 'Gait training (includes stair climbing), each 15 minutes', 'CPT', 'covered'),
(447, 23, '97124', 'Massage, including effleurage, petrissage and/or tapotement (stroking, compression, percussion), each 15 minutes', 'CPT', 'covered'),
(448, 23, '97129', 'Therapeutic interventions focusing on cognitive function and compensatory strategies, direct (one-on-one) patient contact, initial 15 minutes', 'CPT', 'covered'),
(449, 23, '97130', 'Therapeutic interventions focusing on cognitive function, each additional 15 minutes', 'CPT', 'covered'),
(450, 23, '97140', 'Manual therapy techniques (mobilization/manipulation, manual lymphatic drainage, manual traction), one or more regions, each 15 minutes', 'CPT', 'covered'),
(451, 23, '97161', 'Physical therapy evaluation, low complexity', 'CPT', 'covered'),
(452, 23, '97162', 'Physical therapy evaluation, moderate complexity', 'CPT', 'covered'),
(453, 23, '97163', 'Physical therapy evaluation, high complexity', 'CPT', 'covered'),
(454, 23, '97164', 'Physical therapy reevaluation', 'CPT', 'covered'),
(455, 23, '97530', 'Therapeutic activities, direct (one on one) patient contact, use of dynamic activities to improve functional performance, each 15 minutes', 'CPT', 'covered'),
(456, 23, '97535', 'Self care/home management training (ADL and compensatory training, meal preparation, safety procedures, assistive technology), direct one-on-one contact, each 15 minutes', 'CPT', 'covered'),
(457, 23, '97537', 'Community/work reintegration training (shopping, transportation, money management, work environment modification), direct one-on-one contact, each 15 minutes', 'CPT', 'covered'),
(458, 23, '97542', 'Wheelchair management (assessment, fitting, training), each 15 minutes', 'CPT', 'covered'),
(459, 23, '97760', 'Orthotic(s) management and training (including assessment and fitting when not otherwise reported), upper extremity(s), lower extremity(s), and/or trunk, each 15 minutes', 'CPT', 'covered'),
(460, 23, '97761', 'Prosthetic training, upper and/or lower extremity(s), each 15 minutes', 'CPT', 'covered'),
(461, 23, '97763', 'Orthotic(s)/prosthetic(s) management and/or training, subsequent encounter, each 15 minutes', 'CPT', 'covered'),
(462, 23, '99509', 'Home visit for assistance with activities of daily living and personal care', 'CPT', 'covered'),
(463, 23, '0791T', 'Motor-cognitive, semi-immersive virtual reality-facilitated gait training, each 15 minutes', 'CPT', 'not_covered'),
(464, 23, '97039', 'Unlisted modality (specify type and time if constant attendance)', 'CPT', 'related'),
(465, 23, '97139', 'Unlisted therapeutic procedure (specify)', 'CPT', 'related'),
(466, 23, '97150', 'Therapeutic procedure(s), group (2 or more individuals)', 'CPT', 'related'),
(467, 23, 'G0151', 'Services performed by a qualified physical therapist in the home health or hospice setting, each 15 minutes', 'HCPCS', 'covered'),
(468, 23, 'G0159', 'Services performed by a qualified physical therapist, in the home health setting, in the establishment or delivery of a safe and effective therapy maintenance program, each 15 minutes', 'HCPCS', 'covered'),
(469, 23, 'S9131', 'Physical therapy, in the home, per diem', 'HCPCS', 'covered'),
(470, 23, 'G0152', 'Services performed by a qualified occupational therapist in the home health or hospice setting, each 15 minutes', 'HCPCS', 'related'),
(471, 23, 'G0153', 'Services performed by a qualified speech-language pathologist in the home health or hospice setting, each 15 minutes', 'HCPCS', 'related'),
(472, 23, 'G0157', 'Services performed by a qualified physical therapist assistant in the home health or hospice setting, each 15 minutes', 'HCPCS', 'related'),
(473, 23, 'G2168', 'Services performed by a physical therapist assistant in the home health setting in the delivery of a safe and effective physical therapy maintenance program, each 15 minutes', 'HCPCS', 'related'),
(474, 23, 'S9128', 'Speech therapy, in the home, per diem', 'HCPCS', 'related'),
(475, 23, 'S9129', 'Occupational therapy, in the home, per diem', 'HCPCS', 'related'),
(476, 23, 'A4450', 'Tape, non-waterproof, per 18 square inches', 'HCPCS', 'related'),
(477, 23, 'A4452', 'Tape, waterproof, per 18 square inches', 'HCPCS', 'related');

-- Cigna Therapy Services Physical Therapy (2024 version)
INSERT INTO PolicyCoverage (ID, PolicyID, ProcedureTypeID, Description, LinkToOriginal, StartDate, EndDate, DocumentURL, AddedDate) VALUES
(28, 3, 24, 'Therapy Services - Physical Therapy', 'https://web.archive.org/web/20241204205251/https://www.ashlink.com/ASH/WCMGenerated/CPG_155_Revision_12_-_S_Cigna_tcm17-202326.pdf', '2024-04-15', '2024-12-31', 'docs/cigna/Therapy Services Physical Therapy_041524.pdf', CURRENT_TIMESTAMP);

INSERT INTO PolicyCode (ID, PolicyCoverageID, Code, Description, CodeType, CoverageStatus) VALUES
(478, 28, '97010', 'Application of a modality to 1 or more areas; hot or cold packs', 'CPT', 'covered'),
(479, 28, '97012', 'Application of a modality to 1 or more areas; traction, mechanical', 'CPT', 'covered'),
(480, 28, '97014', 'Application of a modality to 1 or more areas; electrical stimulation (unattended)', 'CPT', 'covered'),
(481, 28, '97018', 'Application of a modality to 1 or more areas; paraffin bath', 'CPT', 'covered'),
(482, 28, '97022', 'Application of a modality to 1 or more areas; whirlpool', 'CPT', 'covered'),
(483, 28, '97024', 'Application of a modality to 1 or more areas; diathermy (eg. microwave)', 'CPT', 'covered'),
(484, 28, '97028', 'Application of a modality to 1 or more areas; ultraviolet', 'CPT', 'covered'),
(485, 28, '97032', 'Application of a modality to 1 or more areas; electrical stimulation (manual), each 15 minutes', 'CPT', 'covered'),
(486, 28, '97033', 'Application of a modality to 1 or more areas; iontophoresis, each 15 minutes', 'CPT', 'covered'),
(487, 28, '97034', 'Application of a modality to 1 or more areas; contrast baths, each 15 minutes', 'CPT', 'covered'),
(488, 28, '97035', 'Application of a modality to 1 or more areas; ultrasound, each 15 minutes', 'CPT', 'covered'),
(489, 28, '97036', 'Application of a modality to 1 or more areas; Hubbard tank, each 15 minutes', 'CPT', 'covered'),
(490, 28, '97110', 'Therapeutic procedure; therapeutic exercises to develop strength and endurance, range of motion and flexibility', 'CPT', 'covered'),
(491, 28, '97112', 'Therapeutic procedure; neuromuscular reeducation of movement, balance, coordination, kinesthetic sense, posture, and/or proprioception', 'CPT', 'covered'),
(492, 28, '97113', 'Therapeutic procedure; aquatic therapy with therapeutic exercises', 'CPT', 'covered'),
(493, 28, '97116', 'Therapeutic procedure; gait training (includes stair climbing)', 'CPT', 'covered'),
(494, 28, '97140', 'Manual therapy techniques (eg, mobilization/manipulation, manual lymphatic drainage, manual traction), 1 or more regions, each 15 minutes', 'CPT', 'covered'),
(495, 28, '97150', 'Therapeutic procedure(s), group (2 or more individuals)', 'CPT', 'covered'),
(496, 28, '97165', 'Occupational therapy evaluation, low complexity', 'CPT', 'covered'),
(497, 28, '97166', 'Occupational therapy evaluation, moderate complexity', 'CPT', 'covered'),
(498, 28, '97167', 'Occupational therapy evaluation, high complexity', 'CPT', 'covered'),
(499, 28, '97168', 'Re-evaluation of occupational therapy established plan of care', 'CPT', 'covered'),
(500, 28, '97530', 'Therapeutic activities, direct one-on-one patient contact, each 15 minutes', 'CPT', 'covered'),
(501, 28, '97535', 'Self-care/home management training (ADL and compensatory training), each 15 minutes', 'CPT', 'covered'),
(502, 28, '97755', 'Assistive technology assessment, direct one-on-one contact, with written report, each 15 minutes', 'CPT', 'covered'),
(503, 28, '97760', 'Orthotic(s) management and training, upper/lower extremity(ies) and/or trunk, initial encounter, each 15 minutes', 'CPT', 'covered'),
(504, 28, '97761', 'Prosthetic training, upper and/or lower extremity(ies), initial encounter, each 15 minutes', 'CPT', 'covered'),
(505, 28, '97763', 'Orthotic(s)/prosthetic(s) management and/or training, subsequent encounter, each 15 minutes', 'CPT', 'covered'),
(506, 28, 'G0129', 'Occupational therapy services in partial hospitalization treatment program, per session (45 min or more)', 'HCPCS', 'covered'),
(507, 28, 'G0152', 'Services performed by a qualified occupational therapist in home health or hospice setting, each 15 minutes', 'HCPCS', 'covered'),
(508, 28, 'G0158', 'Services performed by a qualified occupational therapist assistant in home health or hospice setting, each 15 minutes', 'HCPCS', 'covered'),
(509, 28, 'G0160', 'Services performed by a qualified occupational therapist in home health setting, OT maintenance program, each 15 minutes', 'HCPCS', 'covered'),
(510, 28, 'S9129', 'Occupational therapy, in the home, per diem', 'HCPCS', 'covered'),
(511, 28, '97016', 'Application of a modality to 1 or more areas; vasopneumatic devices', 'CPT', 'not_covered'),
(512, 28, '97026', 'Application of a modality to 1 or more areas; infrared', 'CPT', 'not_covered'),
(513, 28, '97169', 'Athletic training evaluation, low complexity', 'CPT', 'not_covered'),
(514, 28, '97170', 'Athletic training evaluation, moderate complexity', 'CPT', 'not_covered'),
(515, 28, '97171', 'Athletic training evaluation, high complexity', 'CPT', 'not_covered'),
(516, 28, '97172', 'Re-evaluation of athletic training established plan of care', 'CPT', 'not_covered'),
(517, 28, '97537', 'Community/work reintegration training, each 15 minutes', 'CPT', 'not_covered'),
(518, 28, '97545', 'Work hardening/conditioning; initial 2 hours', 'CPT', 'not_covered'),
(519, 28, '97546', 'Work hardening/conditioning; each additional hour', 'CPT', 'not_covered'),
(520, 28, 'S8990', 'Physical or manipulative therapy performed for maintenance rather than restoration', 'HCPCS', 'not_covered'),
(521, 28, 'S9117', 'Back school, per visit', 'HCPCS', 'not_covered'),
(522, 28, '20560', 'Needle insertion(s) without injection(s); 1 or 2 muscle(s)', 'CPT', 'not_covered'),
(523, 28, '20561', 'Needle insertion(s) without injection(s); 3 or more muscles', 'CPT', 'not_covered'),
(524, 28, '97039', 'Unlisted modality (specify type and time if constant attendance)', 'CPT', 'not_covered'),
(525, 28, '97799', 'Unlisted physical medicine/rehabilitation service or procedure', 'CPT', 'not_covered'),
(526, 28, 'S8940', 'Equestrian/hippotherapy, per session', 'HCPCS', 'not_covered'),
(527, 28, 'L3763', 'Elbow wrist hand orthosis, rigid, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(528, 28, 'L3764', 'Elbow wrist hand orthosis, with one or more non-torsion joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(529, 28, 'L3765', 'Elbow wrist hand finger orthosis, rigid, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(530, 28, 'L3766', 'Elbow wrist hand finger orthosis, with one or more non-torsion joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(531, 28, 'L3806', 'Wrist hand finger orthosis, with one or more nontorsion joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(532, 28, 'L3807', 'Wrist hand finger orthosis without joints, prefabricated, customized to fit specific patient', 'HCPCS', 'covered'),
(533, 28, 'L3808', 'Wrist hand finger orthosis rigid without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(534, 28, 'L3891', 'Addition to upper extremity joint, wrist or elbow, concentric adjustable torsion style mechanism, custom fabricated orthotics only, each', 'HCPCS', 'covered'),
(535, 28, 'L3900', 'Wrist hand finger orthosis, dynamic flexor hinge, wrist or finger driven, custom fabricated', 'HCPCS', 'covered'),
(536, 28, 'L3901', 'Wrist hand finger orthosis, dynamic flexor hinge, cable driven, custom fabricated', 'HCPCS', 'covered'),
(537, 28, 'L3905', 'Wrist hand orthosis, with one or more nontorsion joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(538, 28, 'L3906', 'Wrist hand orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(539, 28, 'L3913', 'Hand finger orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(540, 28, 'L3915', 'Wrist hand orthosis, with one or more nontorsion joints, prefabricated, customized to fit specific patient', 'HCPCS', 'covered'),
(541, 28, 'L3917', 'Hand orthosis, metacarpal fracture orthosis, prefabricated, customized to fit specific patient', 'HCPCS', 'covered'),
(542, 28, 'L3919', 'Hand orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(543, 28, 'L3921', 'Hand finger orthosis, with one or more nontorsion joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(544, 28, 'L3923', 'Hand-finger orthosis without joints, prefabricated, customized to fit specific patient', 'HCPCS', 'covered'),
(545, 28, 'L3929', 'Hand finger orthosis, with one or more nontorsion joints, prefabricated, customized to fit specific patient', 'HCPCS', 'covered'),
(546, 28, 'L3931', 'Wrist-hand-finger orthosis, with one or more nontorsion joints, prefabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(547, 28, 'L3933', 'Finger orthosis, without joints, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(548, 28, 'L3935', 'Finger orthosis, nontorsion joint, custom fabricated, includes fitting and adjustment', 'HCPCS', 'covered'),
(549, 28, 'L3956', 'Addition of joint to upper extremity orthosis, any material; per joint', 'HCPCS', 'covered'),
(550, 28, 'L4205', 'Repair of orthotic device, labor component, per 15 minutes', 'HCPCS', 'covered');
